### ISSUE TITLE
Rich Picture da aplicação 

### ISSUE THREAD

**Issue by EsioFreitas** [pax-app/Wiki#1]
Deve ser entregue uma imagem, em boa qualidade, da ideia do aplicativo.

**Comment by gabrielalbino** [comment]
Versão 1.0
![Untitled Diagram](https://user-images.githubusercontent.com/30835149/63065650-4408fb80-bedd-11e9-9ca5-dd55f0954186.png)
DrawIO File: 
[Diagrama Albino.zip](https://github.com/2019-2-arquitetura-e-desenho/Wiki/files/3503894/Diagrama.Albino.zip)

**Comment by EsioFreitas** [comment]
Versão 1.0
![image](https://user-images.githubusercontent.com/34384624/63088504-7c372b00-bf2b-11e9-9903-5a2a14d57e18.png)

**Comment by rogerioo** [comment]
Versão 1.0

![RP-Roger-V1](https://user-images.githubusercontent.com/42387946/63220512-a2451100-c15f-11e9-8df5-8302b1d108c9.jpg)

**Comment by MarcosNBJ** [comment]
Versão 1.0
![RichPictureMarcos](https://user-images.githubusercontent.com/14258378/63220993-99a50880-c168-11e9-9af9-e1bd4f3f7bbb.png)

**Comment by kaiquebuilds** [comment]
Versão 1.0

![Meraki (1)-1](https://user-images.githubusercontent.com/14828276/63226924-e283ae00-c1b6-11e9-9359-23730eb1e6a8.png)

**Comment by lucasdutraf** [comment]
Rich Picture v1.0
![rp](https://user-images.githubusercontent.com/31940073/63227075-0cd66b00-c1b9-11e9-88cb-2536b1cf77f1.jpg)

**Comment by fepas** [comment]
Rich Picture v1.0
![rp](https://i.imgur.com/HSX77gT.jpg)

**Comment by youssef-md** [comment]
Não tem os desenhos mas prometo uma v2 com
![photo_2019-08-18_14-00-44](https://user-images.githubusercontent.com/29265857/63227780-aead8600-c1c0-11e9-8b2b-366ea852ec27.jpg)

**Comment by Matheusss03** [comment]
Tá bem simples, mas assim que eu aprender a mexer no app vai ser melhorado
![RP - V1](https://user-images.githubusercontent.com/17857701/63228140-870cec80-c1c5-11e9-8a9a-3a83c5b74422.png)

**Comment by FabianaRibas** [comment]
RichPicture V1.0
![RichPicturev1 0](https://user-images.githubusercontent.com/38467658/63228571-4fa13e80-c1cb-11e9-9869-ad241caecf0e.jpeg)
