### ISSUE TITLE
Configurar ambiente de desenvolvimento

### ISSUE THREAD

**Issue by lucasdutraf** [pax-app/Wiki#103]
# Descrição da Issue
Criar e configurar containers, implementar pipeline de testes e deploy contínuo.

## Tasks:
- [ ] User
- [ ] Report
- [ ] Category
- [ ] Pax
- [ ] Rating
- [ ] Chat
- [ ] Gateway
- [ ] Front-end

# Critérios de Aceitação
* Todos os serviços possuírem seus respectivos dockers, pipelines e ambiente de produção

**Comment by FabianaRibas** [comment]
Comparativo entre GitLab CI vs Travis CI
https://about.gitlab.com/devops-tools/travis-ci-vs-gitlab.html

**Comment by FabianaRibas** [comment]
Comparativo entre GitLab CI vs Travis CI vs Jenkins CI
https://stackshare.io/stackups/gitlab-ci-vs-jenkins-vs-travis-ci

**Comment by FabianaRibas** [comment]
Diversas pesquisas que fiz, a maioria aponta para o Travis CI pelos seguinte motivos:
- Sincronização com o GitHub
- Cria e testa automaticamente alterações incrementais de código
- Gerencia implantações e notificações
- Gratuito para projetos de código aberto
- Suporta uma ampla variedade de linguagens de programação
- Suporte de software personalizável
- Planos empresariais disponíveis

**Comment by fepas** [comment]
https://codeclimate.com/
Acho que o Code Climate também pode ser de grande ajuda.

**Comment by lucasdutraf** [comment]
@fepas Com certeza! Ele tem boas métricas que podemos utilizar posteriormente
