### ISSUE TITLE
Estilizar a Wiki

### ISSUE THREAD

**Issue by EsioFreitas** [pax-app/Wiki#109]
# Descrição da Issue
Atualizar os style da wiki respeitando o documento de identidade visual

## Tasks:
- [ ] Navbar Resposiva
- [ ] Dropdown das sprints
- [ ] REAME inicial
- [ ] Colaboradores

# Critérios de Aceitação
* Colocar artefato na Wiki
* cards dos membros
* Sidebar com drop

**Comment by lucasdutraf** [comment]
Fé pra isso
