### ISSUE TITLE
US20 - Categorias

### ISSUE THREAD

**Issue by EsioFreitas** [pax-app/Wiki#141]
# Descrição da Issue
O prestador de serviço deve ter as categorias para adicionar no seu perfil 

## Tasks:
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

# Critérios de Aceitação
* Frontend e backend implementados

**Comment by FabianaRibas** [comment]
tela do app no protótipo de alta fidelidade relacionada a essa issue:
https://github.com/pax-app/Wiki/blob/111_high_fidelity_prototype/assets/prototipo-alto-nivel/tornar-prestador-fluxo.png
