### ISSUE TITLE
US21 - Atribuir faixas de preço 

### ISSUE THREAD

**Issue by lucasdutraf** [pax-app/Wiki#142]
# Descrição da Issue

Eu, como prestador de serviço , desejo atribuir faixas de preço aos meus serviços para determinar o quanto eu quero receber

## Tasks:
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

# Critérios de Aceitação
* Front-end e back-end implementados

**Comment by rogerioo** [comment]
Abrir PR
