### ISSUE TITLE
Versão 2.0 do Rich Picture geral

### ISSUE THREAD

**Issue by lucasdutraf** [pax-app/Wiki#15]
# Descrição da Issue
Foi acordado em reunião a necessidade de unificar, em uma só visão que represente o grupo, todos os rich pictures produzidos pelo grupo na issue #1 

## Tasks:
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

# Critério de aceitação
- [ ] O documento deve estar na Wiki
- [ ] O grupo deve acordar com a visão explicitada no rich picture

**Comment by rogerioo** [comment]
Versão 1.0
![rp_geral_v1](https://user-images.githubusercontent.com/42387946/63486950-d2eaba80-c47f-11e9-9878-f6f5774a945b.png)

Aguardo aprovação do grupo!

**Comment by EsioFreitas** [comment]
@rogerioo Adiciona a troca que tem no fluxo. Por exemplo dinheiro, felicidade, tempo...

**Comment by lucasdutraf** [comment]
Reitero o comentário do @EsioFreitas , mas ficou sensacional! Parabéns!

**Comment by rogerioo** [comment]
Versão 2.0
![rp_geral_v2](https://user-images.githubusercontent.com/42387946/63486827-6a9bd900-c47f-11e9-930c-946cdbf35f7c.png)
