### ISSUE TITLE
US27 - Lista de Serviços

### ISSUE THREAD

**Issue by lucasdutraf** [pax-app/Wiki#162]
# Descrição da Issue
Eu, como	usuário do sistema	, desejo ter acesso a uma lista de serviços	para	poder conseguir contratar um serviço
## Tasks:
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

# Critérios de Aceitação
* O usuário deve ter acesso a lista de serviços gerais
* Clicando em um serviço geral, o usuário deve ter acesso a uma lista de serviços específicos por categoria
* Seguir protótipo de alta fidelidade
* As quatro telas abaixo estarem implementadas
* Apenas o front-end é necessário, o back-end foi implementado em https://github.com/pax-app/Category/pull/2
![image](https://user-images.githubusercontent.com/31940073/66431862-39f20d80-e9f3-11e9-9611-b07e57e8be0e.png)

**Comment by lucasdutraf** [comment]
@fepas @FabianaRibas Coloquem as Tasks!

**Comment by fepas** [comment]
OKOK
