### ISSUE TITLE
Rich Picture da visão do contratante de serviços

### ISSUE THREAD

**Issue by lucasdutraf** [pax-app/Wiki#17]
# Descrição da Issue
Conforme discutido, é necessária a elaboração de um rich picture levando em consideração o ponto de vista do contratante de um serviço que usará a aplicação. Se baseando, também, na issue #1 .

## Tasks:
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

# Critério de aceitação
 - [ ] O documento deve estar na Wiki
 - [ ]  O grupo deve acordar com a visão explicitada no rich picture

**Comment by FabianaRibas** [comment]
RichPicture_Usuario - V 1.0
![RP_Usuariov1 0](https://user-images.githubusercontent.com/38467658/63480074-efc6c400-c466-11e9-94f1-e63b94f35a62.jpg)

**Comment by lucasdutraf** [comment]
Sensacional! Parabéns pelo trabalho!!

**Comment by FabianaRibas** [comment]
RichPicture_Usuario - V 2.0
![RP_Usuariov2 0](https://user-images.githubusercontent.com/38467658/63556580-cc118580-c51b-11e9-9197-0c6f93a991b8.jpg)
