### ISSUE TITLE
Refatoração de código utilizando Design Patterns

### ISSUE THREAD

**Issue by lucasdutraf** [pax-app/Wiki#174]
# Descrição da Issue
Conforme acordado em grupo, refatoraremos o máximo de código possível e rastrearemos os design patterns implementados visando a dinâmica do dia 25/10.

# Critérios de Aceitação
* Padrão de projeto conforme modelo
* Padrão descrito na Wiki

**Comment by lucasdutraf** [comment]
Singleton implementado para conexão com o banco de dados e migrações! Implementado no serviço de usuários e logo mais em todos os serviços de python. pax-app/User@45f0081

**Comment by MarcosNBJ** [comment]
Melhorando a implementação do mediator na API Gateway e implementando nela algumas das rotas atuais dos serviços para melhor mostrar o padrão.

**Comment by lucasdutraf** [comment]
No serviço de usuários, até o momento, os padrões implementados foram: Decorator, Iterator, Singleton, Strategy e Application Factory

**Comment by FabianaRibas** [comment]
No serviço de Categoria, até o momento, os padrões implementados foram:  Strategy e Facade.
