### ISSUE TITLE
Atualizar documentação das sprints e diagrama de classes

### ISSUE THREAD

**Issue by lucasdutraf** [pax-app/Wiki#187]
# Descrição da Issue
Como houveram refatorações dos serviços para aplicação de padrões de projeto é necessário a confecção de novos diagramas de classes. Além disso, as documentações das sprints também precisam ser atualizadas
## Tasks:
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

# Critérios de Aceitação
* Colocar artefatos na Wiki

**Comment by rogerioo** [comment]
Dividir em duas issues.

**Comment by rogerioo** [comment]
Documentação de sprint pronta, mas falta abrir o PR

**Comment by rogerioo** [comment]
Atualização de diagramas vai mudar o foco por conta do DAS.
