### ISSUE TITLE
Configurar CI/CD dos microsserviços do projeto

### ISSUE THREAD

**Issue by lucasdutraf** [pax-app/Wiki#188]
# Descrição da Issue
Estamos em um ponto do projeto o qual é necessário possuirmos deploys dos nossos serviços para melhor andamento do desenvolvimento da aplicação.

# Critérios de Aceitação
* Deploy automatizado de todos os microsserviços com pipeline que parta do envio do commit para a branch develop e chegue até o deploy do serviço em uma URL pública
* Integração contínua em todos os microsserviços

**Comment by rogerioo** [comment]
Marcos disse que está com os travis.yml prontos, só precisa abrir o PR

**Comment by MarcosNBJ** [comment]
Issue cumprida com a utilização do [Travis](https://travis-ci.org/) e do [Heroku](https://dashboard.heroku.com/). Todos os microsserviços podem ser acessados através das seguintes URLs:

[Gateway](http://pax-gateway.herokuapp.com/)
[User](http://pax-user.herokuapp.com/)
[Review](http://pax-review.herokuapp.com/)
[Report](http://pax-report.herokuapp.com/)
[Pax](http://pax-pax.herokuapp.com/)
[Category](http://pax-category.herokuapp.com/)
[Chat](http://pax-chat.herokuapp.com/)

A pipeline de deploy foi configurada de tal forma que qualquer commit que chegue a branch devel de qualquer um destes serviços dá início a um processo no Travis que realiza o deploy desse commit na URL do dado serviço no Heroku.

Para garantir a equivalência entre o visto localmente e no ambiente de produção o deploy no heroku é feito utilizando containers do docker.

**Comment by rogerioo** [comment]
Mano, ficou sensacional! Parabéns pelo trabalho :heart:
