### ISSUE TITLE
US54 - Eu, como usuário do sistema, desejo conseguir enviar arquivos pelo chat

### ISSUE THREAD

**Issue by lucasdutraf** [pax-app/Wiki#191]
# Descrição da Issue
Eu, como	usuário do sistema	, desejo	conseguir enviar arquivos pelo chat para trocar informações 
## Tasks:
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

# Critérios de Aceitação
* Estar de acordo com o protótipo de alta fidelidade
* Usuário deve conseguir enviar uma imagem
* Aplicação de padrões de projeto
  * Adição do padrão na Wiki
![image](https://user-images.githubusercontent.com/31940073/67735711-b751e200-f9e3-11e9-859c-a6184affb9f9.png)

**Comment by rogerioo** [comment]
Issue concluída esperando PR ser aceito!
