### ISSUE TITLE
Fluxo de Avaliação

### ISSUE THREAD

**Issue by fepas** [pax-app/Wiki#197]
# Descrição da Issue
Fluxo de avaliação do prestador e usuário ao finalizar um serviço

## Tasks:
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

# Critérios de Aceitação
![Screenshot from 2019-11-11 21-03-00](https://user-images.githubusercontent.com/29265857/68630636-ad8dab80-04c6-11ea-8b0d-ec0c72a30b1e.png)

**Comment by lucasdutraf** [comment]
Acabou!! E wontfix btw
