### ISSUE TITLE
5W2H da aplicação

### ISSUE THREAD

**Issue by EsioFreitas** [pax-app/Wiki#2]
Cada um deve entregar uma tabela em markdown do 5W2H da aplicação. 

Referencias:
![image](https://user-images.githubusercontent.com/34384624/63062850-bb845e00-bed0-11e9-93c3-b6540a039944.png)

**Comment by gabrielalbino** [comment]
Versão 1.0


| O que?                                                                            | Quem?                                                                                                                            | Onde?                              | Porque?                                                                                                                                                       | Quando?                                                      | Como?                                                                                                                                                                                                                                                 | Quanto?                                                                                                      |
|-----------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------|------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------|
| Oferecer e gerenciar prestação de serviços gerais por trabalhadores "Freelancers" | Poderá ser utilizado por pessoas que oferecem seu serviço ou por pessoas que procuram um serviço e está disposto a pagar por ele | No celular, acessando o aplicativo | Porque pessoas precisam trabalhar e porque pessoas ás vezes não tem tempo de realizar algumas atividades e estão dispostas a pagar para alguém fazer por elas | Quando surgir necessidade de contratar ou prestar um serviço | Possibilitando que um usuário encontre algum serviço de seu interesse e providenciando um trabalhador para aquele serviço, garantindo para o contratante que o serviço será prestado e garantindo o pagamento para o contrato que irá fazer o serviço | Será cobrado o valor do serviço + uma taxa, para o prestador ele receberá o valor total do serviço prestado. |

**Comment by lucasdutraf** [comment]
Versão 1.0


| O que?                                                                            | Quem?                                                                                                                            | Onde?                              | Porque?                                                                                                                                                       | Quando?                                                      | Como?                                                                                                                                                                                                                                                 | Quanto?                                                                                                      |
|-----------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------|------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------|
| Unificar e divulgar serviços prestados por trabalhadores independentes | Profissionais que tem interesse em executar serviços de forma independente e pessoas que tem interesse em contratar os serviços oferecidos por esses profissionais | Numa aplicação disponível para celulares - Android e IOS | Pela carência de uma aplicação consistente e bem formulada que a população possui, facilitando assim, atividades cotidianas que ainda são realizadas através de métodos arcaircos e de pouco alcance | Quando houver a necessidade do contratante e a disponibilidade do contratado | Através de um contato inicial na plataforma, contratante e contratado estabelecerão regras e necessidades de ambas as partes após o serviço ser requisitado na aplicação | Preço ofertado pelo prestador de serviços + taxas da aplicação |

**Comment by EsioFreitas** [comment]
Versão 1.0


| O que?                                                                            | Quem?                                                                                                                            | Onde?                              | Porque?                                                                                                                                                       | Quando?                                                      | Como?                                                                                                                                                                                                                                                 | Quanto?                                                                                                      |
|-----------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------|------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------|
| Facilitar o contato entre cliente e prestador de serviço dando foco em qualidade e segurança na relação entre eles | Toda e qualquer pessoa que quer contratar alguém para fazer um serviço | Em aplicações mobile - Android e IOS | Pois há dificuldades de encontrar e de ver avaliações de pessoas que prestam serviços | Quando precisar de contratar alguém | Pelo aplicativo, a pessoa pode solicitar o serviço do contratado e marcar o dia de fazer a atividade | Preço ofertado pelo prestador de serviços + taxas da aplicação |

**Comment by MarcosNBJ** [comment]
Versão 1.0

|O que ?|Quem ?|Onde ?|Porque ?|Quando ?|Como ?|Quanto ?|
|--|--|--|--|--|--|--|
|Construir uma ponte entre prestadores de serviços gerais e consumidores|Profissionais independentes de quaisquer áreas que precisam de um meio para chegar aos seus clientes. Assim como pessoas que por suas necessidades diárias precisam de um meio mais fácil para contratar serviços gerais | Aplicativo para dispositivos mobile|Porque atualmente as pessoas apresentam necessidades diárias de contratar diversos serviços e para uma grande parte destes existe uma quantidade satisfatória de profissionais, porém falta um canal de comunicação que ligue esses dois grupos e facilite a busca e contratação de um prestador de serviço | A qualquer hora que alguém precise de um serviço |A pessoa que busca contratar um serviço acessa o aplicativo, busca o serviço desejado, e então contrata o prestador que melhor atender as suas necessidades de horário e especificações do serviço. O prestador por sua vez pode aceitar ou negar o serviço solicitado, e ao aceitar devera realiza-lo para então receber o pagamento| O aplicativo é de acesso gratuito, já a contratação de um serviço é precificada como sendo o valor do serviço adicionado a uma taxa do aplicativo|

**Comment by rogerioo** [comment]
Oi

**Comment by rogerioo** [comment]
Versão 1.0


| O que? | Quem? | Onde? | Porque? | Quando? | Como? | Quanto? |
|:------:| :----:| :----:| :-----: | :-----: | :---: | :-----: |
| Uma aplicativo mobile que favoreça a fácil comercialização de serviços | Pessoas que tem suas vidas atarefadas e não tem tempo de relizar tarefas corriqueiras | Plataforma mobile | O mercado de serviços não é tão acessível, uma vez que as pessoas demandam recomendação previa dos prestadores | A qualquer instante que tenha a necessidade de solicitar um serviço, desde que o prestador tenha disponibilidade | O prestador cria sua página e disponibiliza os seus serviços, e as pessoas pesquisam pelo serviço e a aplicação recomenda o mais próxima e bem recomendado que o realize | O valor é determinado pelo prestador |

**Comment by FabianaRibas** [comment]
Versão 1.0

| O que? | Quem? | Onde? | Porque? | Quando? | Como? | Quanto? |
|:------:| :----:| :----:| :-----: | :-----: | :---: | :-----: |
| App  que facilita a comunicação entre pessoas que procuram serviços diversos e trabalhadores que desejam prestar serviço |  Pessoas que procuram serviços e prestadores do mesmo | Aplicativo para mobile | Difícil acesso ao contato de profissionais que prestam um determinado serviço além da diversidade de profissionais | No momento em que o usuário sente a  necessidade de contratar um serviço | Na visão do usuário, a pessoa que necessitar do serviço procura, no app, um trabalhador disponível para realizar o trabalho, sendo de ambos a responsabilidade do contrato. Na visão do trabalhador ele deve criar um perfil e descrever seu serviço além de aceitar ou não o serviço requisitado. | Preço ofertado pelo prestador de serviços + taxas da aplicação |

**Comment by kaiquebuilds** [comment]
Versão 1.0

| O que? | Quem? | Onde? | Porque? | Quando? | Como? | Quanto? |
|:------:| :----:| :----:| :-----: | :-----: | :---: | :-----: |
| App que conecta prestadores de serviço a clientes, auxiliando no processo de contratar e agendar o serviço | Prestadores de serviços e pessoas que querem contratar | Aplicativo para dispositivos móveis | Dificuldade de encontrar profissionais confiáveis e ter um catálogo para poder escolher por preço | No momento em que o usuário sente a  necessidade de contratar um serviço | Pesquisando serviço no catálogo do app, escolhendo um profissional e solicitando o contato do mesmo | Preço cobrado pelo profissional - com a taxa do app embutida |

**Comment by fepas** [comment]
Versão 1.0

| O que? | Quem? | Onde? | Porque? | Quando? | Como? | Quanto? |
|:------:| :----:| :----:| :-----: | :-----: | :---: | :-----: |
| Alicação voltada á conexão entre prestador de serviço e contratante interessado | Prestadores e Contratantes | Aplicação Mobile/Web | Centralizar mercado de serviços | Quando um usuário necessita de um serviço | Utilizando o aplicativo | Depende do caso: Serviço, preço do prestador, APP: gratuito, Prestador Premium: Pago |
