### ISSUE TITLE
Diagrama de Bancos

### ISSUE THREAD

**Issue by EsioFreitas** [pax-app/Wiki#214]
# Descrição da Issue
Diagrama do Banco de Dados relacional que condiz com a modelagem atual

## Tasks:
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

# Critérios de Aceitação
* Colocar artefato na Wiki

**Comment by FabianaRibas** [comment]
Feito, esperando aceitarem o PR!!!

**Comment by lucasdutraf** [comment]
Issue feita
