### ISSUE TITLE
Documento de definição de projeto

### ISSUE THREAD

**Issue by lucasdutraf** [pax-app/Wiki#22]
# Descrição da Issue
A issue se resume a criação de um documento que explicite todo o processo criativo do time, incluindo cada documento criado, decisão tomada e insights que o grupo foi adquirindo com o passar do tempo.

## Tasks:
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

# Critérios de aceitação
- [ ] Documento deve estar na Wiki

**Comment by MarcosNBJ** [comment]
Documento criado pondo em foco como foi o processo da equipe para a tomada das decisões que levaram a ideia escolhida a chegar em seu corpo atual e o que foi produzido com ela. Pull Request feito para Wiki
