### ISSUE TITLE
Entrevista com possível usuário

### ISSUE THREAD

**Issue by EsioFreitas** [pax-app/Wiki#4]
Fazer entrevista com um possivel usuário do sistema. 
Deve entregar um áudio/video da entrevista, as perguntas e resposta do usuário e outros insides, se tiver

**Comment by lucasdutraf** [comment]
# Roteiro da Entrevista v1.0
#### Entrevistados: Abrahão Ferreira do Nascimento e Eurenice Dutra

## Perguntas

1. Qual meio você geralmente utiliza para contratar prestadores de serviços?  

2. Com qual frequência você costuma contratar prestadores de serviço?  

3. Você já se deparou com algum empecilho na hora de estabelecer esse tipo de contato? Se sim, qual?  

4. Como você custuma verificar se o serviço da pessoa contratado é de boa qualidade?  

5. Existe algum critério para contratar um prestador de serviços?  

6. Você utilizaria uma plataforma para contratar prestadores de serviços baseado na sua necessidade?

7. A opinião de outros contratantes sobre um prestador de serviço é um ponto chave para você efetuar a contratação?

8. Qual método de pagamento você costuma usar o prestador de serviço contratado?

**Comment by lucasdutraf** [comment]
Gente, fiz uma v1.0 da entrevista! Por favor, validem. Qualquer feedback e ideia são bem vindos. @2019-2-arquitetura-e-desenho/devs

**Comment by EsioFreitas** [comment]
9 - Teria algum motivo para não usar um aplicativo que contrate prestadores de serviço? Quais?

**Comment by kaiquebuilds** [comment]
## Perguntas

1. Qual meio você geralmente utiliza para contratar prestadores de serviços?
2. Com qual frequência você costuma contratar prestadores de serviço?
3. Você já se deparou com algum empecilho na hora de estabelecer esse tipo de contato? Se sim, qual?
4. Como você costuma verificar se o serviço da pessoa contratado é de boa qualidade?
5. Existe algum critério para contratar um prestador de serviços?
6. Você utilizaria uma plataforma para contratar prestadores de serviços baseado na sua necessidade?
7. A opinião de outros contratantes sobre um prestador de serviço é um ponto chave para você efetuar a contratação?
8. Qual método de pagamento você costuma usar o prestador de serviço contratado?
9. Teria algum motivo para não usar um aplicativo que contrate prestadores de serviço? Quais?
10. **Pergunta extra** (feita baseada nas respostas do entrevistado 1, investigando uma possível oportunidade) - O fato de um prestador de serviços aceitar pagamento por cartão de crédito aumenta as suas chances de optar pelo mesmo?

## Respostas entrevistado 1

1. "A princípio por indicação, sempre procuro alguém que já conheça quem faça o serviço, caso ninguém conheça procuro na internet".
2. "Só quando é necessário, mas sem frequência certa".
3. "Não, nunca aconteceu".
4. "Por isso vou para a indicação primeiro, caso seja pela internet, nunca vou pelo mais barato".
5. "Não. Vejo se tem indicação ou não e vou pelo preço. Se for uma empresa, vejo quanto tempo de de mercado, as instalações físicas".
6. "Óbvio. Lógico".
7. "Com certeza".
8. "Acho mais fácil débito em conta, mas a maioria escolhe boleto".
9. "Se fosse pago eu não usaria".
10. "Lógico!".

## Respostas entrevistado 2
O áudio dessa entrevista pode ser encontrado no nossos arquivos do Drive.

1. Por Indicação.
2. Raramente.
3. Sim, você não tem garantia que o serviço é bom e se não for indicação, você não sabe a qualidade de do serviço. Se for indicação, você não tem o contato da pessoa, caso a pessoa que indica não o tenha.
4. Se quem está indicando informa que o serviço é de qualidade, você tem que acreditar.
5. Se a pessoa é confiável.
6. Usaria.
7. Sim.
8. Dinheiro.
9. Não, só desconheço algum que tenha.
10. Sim, com certeza.

**Comment by lucasdutraf** [comment]
# Roteiro da Entrevista v2.0

## Perguntas

1. Qual meio você geralmente utiliza para contratar prestadores de serviços?  

2. Com qual frequência você costuma contratar prestadores de serviço?  

3. Você já se deparou com algum empecilho na hora de estabelecer esse tipo de contato? Se sim, qual?  

4. Como você costuma verificar se o serviço da pessoa contratada é de boa qualidade?  

5. Existe algum critério para contratar um prestador de serviços?  

6. Você utilizaria uma plataforma para contratar prestadores de serviços baseado na sua necessidade?

7. A opinião de outros contratantes sobre um prestador de serviço é um ponto chave para você efetuar a contratação?

8. Qual método de pagamento você costuma usar para pagar o prestador de serviço contratado?  

9. Teria algum motivo para não usar um aplicativo que contrate prestadores de serviço? Quais?

**Comment by lucasdutraf** [comment]
# Respostas com base no Roteiro da Entrevista v2.0
#### Entrevistado: Abrahão Ferreira do Nascimento

## Respostas

1. Internet e indicações.

2. De acordo com a necessidade, não tem uma frequência fixa.(Uma melhor pergunta seria "Em que frequência e circunstância você contrata um prestador de serviços")

3. Disponibilidade nos finais de semana (domingos) e feriados, preço abusivo, serviço mal prestado.

4. Indicação, internet disponibiliza alguma informações nos comentários, consulta ao PROCON, reclame aqui.

5. O primeiro critério é a qualidade do serviço, feedback de outros contratantes, disponibilidade para realização do serviço e o preço justo. A disponibilidade é muito importante, pois no meu caso, os finais de semana são os únicos períodos que eu posso receber um prestador de serviços, também alguns casos específicos como em emergências durante finais de semana ou alguma hora após o horário comercial.  

6. Com certeza. Pois a plataforma, como o Uber, é uma plataforma que se baseia na minha necessidade, então, com certeza.  

7. Sim, claro. O feedback dos outros é fundamental para confirmar a qualidade do serviço prestado.

8. Cartão de crédito e se for acordado entre as partes, dinheiro ou transferência bancária. A forma de pagamento varia, porém percebo que a maioria de pequenos prestadores de serviço que já contratei preferem dinheiro em espécie. As máquinas de cartão de crédito geram taxas, por isso preferência por dinheiro.

9. Um motivo seria a confibilidade no aplicativo, pois se esse app não forncece nenhuma funcionalidade como feedback de outros contratantes, baixa quantidade de ofertas ou não deixe claro a qualidade dos prestadores de serviços (Avaliação e comentários).  

**Feedback: muito necessária a prestação de serviços para idosos e seria perfeita para a realidade de muita gente que conheço.**
