### ISSUE TITLE
Ideias de nomes para aplicação

### ISSUE THREAD

**Issue by EsioFreitas** [pax-app/Wiki#40]
# Descrição da Issue
Criar um nome para a aplicação, atendendo o escopo do projeto.

# Critérios de Aceitação
* Um ou mais ideias de nomes

## Obs.: 
Tarefa não obrigatória

**Comment by rogerioo** [comment]
Me inspirei em nomes de aplicativos que não se rementem diretamente ao nicho o qual está inserido (Uber, Rappi) e quis algo que tivesse uma pronuncia forte e marcante para destacar nossa aplicação, desta forma pensei no seguinte nome:
* **Rasch**, do alemão, que significa rápido. Isso pode auxiliar a ideia que pretendemos dar ao nosso app para as pessoas poderem ganhar tempo

**Comment by FabianaRibas** [comment]
Pensei em nomes que remetessem a troca de esforço por uma recompensa
e me deparei com dois caracteres do calendário maia chamados

- **PAX** -> tempo de plantio;

- **KUMKU** -> deposito de grãos;

Além deles também achei interessante a tradução de rápido em havaiano:

- **WIKIWIKI** -> rápido

Mas como o app é direcionado ao publico brasileiro, acredito que seja melhor um nome em **Pt-Br**

**Comment by fepas** [comment]
> Pensei em nomes que remetessem a troca de esforço por uma recompensa
> e me deparei com dois caracteres do calendário maia chamados
> 
> * **PAX** -> tempo de plantio;
> * **KUMKU** -> deposito de grãos;
> 
> Além deles também achei interessante a tradução de rápido em havaiano:
> 
> * **WIKIWIKI** -> rápido
> 
> Mas como o app é direcionado ao publico brasileiro, acredito que seja melhor um nome em **Pt-Br**

Curti o WIKIWIKI

**Comment by youssef-md** [comment]
Peguei as traduções de algumas palavras importantes para nosso app
Serviço -> Português
Diens -> Africâner
Sabis -> Hauçá
ọrụ -> Igbo

Pensei em trazer a palavra "Proposta" já que isso vai ser o que antecede um contrato feito:
Proposta -> Português
Propono -> Esperanto
Togra -> Irlandês
öneri -> Turco
Taklif -> Uzbeque

E pensei na palavra "contrato":
Contrato -> português
kontrak -> Africâner
akad -> Sundanês

**Comment by lucasdutraf** [comment]
@youssef-md Gostei de propono, diens e sabis

**Comment by rogerioo** [comment]
@youssef-md Latim:
Serviço -> Officium
Serviços -> Muneris

**Comment by rogerioo** [comment]
Ainda dá pra fazer um slogan:

**Officium**: *serviços do dia-a-dia*

**Comment by rogerioo** [comment]
De acordo com reunião via Hangouts realizada no dia 28/08 o nome decidido, por votação, foi **Pax** (sugerido e explicado pela @FabianaRibas ).
