### ISSUE TITLE
Criar wireframe da aplicação 

### ISSUE THREAD

**Issue by EsioFreitas** [pax-app/Wiki#41]
# Descrição da Issue
Criar um wireframe que mostre o fluxo da aplicação de acordo com os entregáveis das issues (Rich Pictures e Brainstorm) #1  #16 #17 #9 

# Critérios de Aceitação
* Ter um ou mais documentos que mostre a tela e fluxo da aplicação
* Seguir o fluxo dos documentos lincados nas issues

**Comment by EsioFreitas** [comment]
V1 

![photo_2019-08-25_13-44-09](https://user-images.githubusercontent.com/34384624/63653075-7537c600-c73e-11e9-94c7-806b29128e56.jpg)
![photo_2019-08-25_13-44-13](https://user-images.githubusercontent.com/34384624/63653076-7537c600-c73e-11e9-9362-922206243cc0.jpg)
![photo_2019-08-25_13-44-17](https://user-images.githubusercontent.com/34384624/63653077-75d05c80-c73e-11e9-96d3-3b637020aeb2.jpg)

**Comment by gabrielalbino** [comment]
Fluxo do cadastro de prestador de serviço + Acesso ao menu do prestador de serviço
![iPhone X](https://user-images.githubusercontent.com/30835149/63653609-96e87b80-c745-11e9-8c9d-da0b4737ebfd.png)
![iPhone X-5](https://user-images.githubusercontent.com/30835149/63653614-97811200-c745-11e9-9c9c-ce458a115668.png)
![iPhone X-1](https://user-images.githubusercontent.com/30835149/63653610-96e87b80-c745-11e9-86c4-02127d614906.png)
![iPhone X-2](https://user-images.githubusercontent.com/30835149/63653611-97811200-c745-11e9-8157-cc59c18ef81b.png)
![iPhone X-3](https://user-images.githubusercontent.com/30835149/63653612-97811200-c745-11e9-9d25-420bc4fe0047.png)
![iPhone X-4](https://user-images.githubusercontent.com/30835149/63653613-97811200-c745-11e9-819f-c49bb3e492a6.png)
![iPhone X-6](https://user-images.githubusercontent.com/30835149/63653615-97811200-c745-11e9-82d8-bec4319f3956.png)
![iPhone X-7](https://user-images.githubusercontent.com/30835149/63653616-9819a880-c745-11e9-8884-adbb103d9b4e.png)

**Comment by kaiquebuilds** [comment]
## Fluxos V1

![Fluxo Pax](https://user-images.githubusercontent.com/14828276/64071011-cd8f2c00-cc46-11e9-8d63-7e839615a781.png)

## Wireframes

Listei as principais telas de acordo com o fluxo e fiz uma versão de baixa fidelidade de cada uma. Elas podem ser encontradas [aqui](https://www.figma.com/file/aHrb3wHq5lV08AnOAVGp58/Wireframes-Pax?node-id=0%3A1)

**Comment by rogerioo** [comment]
@kaiqueborges Ficou muito lindo! Parabéns ❤

**Comment by youssef-md** [comment]
O fluxo e o Wireframe ficaram muito bons @kaiqueborges  :heart:

**Comment by rogerioo** [comment]
Esses wireframes tem que entra na Wiki em formato de documento
