### ISSUE TITLE
Criar Quadro de Conhecimento 

### ISSUE THREAD

**Issue by EsioFreitas** [pax-app/Wiki#48]
# Descrição da Issue
Criar o quadro de conhecimento do grupo

# Critérios de Aceitação
* Colocar artefato na Wiki
* Abranger as tecnologias que podem ser usadas

**Comment by EsioFreitas** [comment]
@FabianaRibas Add flutter e dart ao em vez de digital ocean e zappa

**Comment by FabianaRibas** [comment]
@EsioFreitas adicionei o dart e o flutter ao quadro ;)
https://docs.google.com/spreadsheets/d/17-oYtfGoAp5dQNvqCOQ90ipwWl9ZP_3dQ57It1uAocE/edit?usp=sharing

**Comment by rogerioo** [comment]
A @FabianaRibas já criou o quadro e adaptou ao escopo do projeto, mas falta o @MarcosNBJ e o @gabrielalbino preencherem

**Comment by rogerioo** [comment]
O quadro já se encontra disponível no drive do time e vai ser preenchido semanalmente de forma a ajudar a ajustar os pareamentos da issues.
