### ISSUE TITLE
Pesquisas de tecnologias a serem utilizadas

### ISSUE THREAD

**Issue by lucasdutraf** [pax-app/Wiki#49]
# Descrição da Issue
Temos que entender melhor, antes da elaboração de um documento de arquitetura, as tecnologias que melhores contemplam nossas necessidades para o desenvolvimento completo do software proposto.

## Tasks:
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

# Critérios de Aceitação
* Colocar artefato na Wiki
* Elaborar um padrão para cada tecnologia a ser explicitada

**Comment by rogerioo** [comment]
Documento já disponível na wiki
