### ISSUE TITLE
Analise de protocolo

### ISSUE THREAD

**Issue by EsioFreitas** [pax-app/Wiki#5]
Deve entregar o documento de analise de protocolo com os arquivos para rastreabilidade

**Comment by kaiquebuilds** [comment]
Como contratar profissionais geralmente não é algo planejado. Não havia tempo para agendar uma análise de protocolo, que também é uma técnica para processos específicos. O esforço desta tarefa foi realocado para duas [entrevistas](https://github.com/2019-2-arquitetura-e-desenho/Wiki/issues/4)
