### ISSUE TITLE
NFR

### ISSUE THREAD

**Issue by EsioFreitas** [pax-app/Wiki#51]
# Descrição da Issue
Produzir NFR

## Tasks:
- [x] Construir o modelo SIG com m Draw IO
- [ ] Realizar uma inspeção no NFR com a checklist realizada semestre passado

# Critérios de Aceitação
* Colocar artefato na Wiki

**Comment by rogerioo** [comment]
Versão 1.0 

Por: @rogerioo e @youssef-md 

É necessário zoom para poder ler

![NFRPax_V1-NFR Modelo](https://user-images.githubusercontent.com/42387946/64071590-d1757b00-cc53-11e9-80e4-dfc27e99086c.png)
![NFRPax_V1-Interferências](https://user-images.githubusercontent.com/42387946/64071593-d63a2f00-cc53-11e9-88cc-49e9512d9af0.png)
