### ISSUE TITLE
Manual de Identidade Visual da Aplicação

### ISSUE THREAD

**Issue by EsioFreitas** [pax-app/Wiki#52]
# Descrição da Issue
Produzir o manual de identidade visual. Segue modelo https://fga-eps-mds.github.io/2018.2-Kalkuli/docs/idVisual

## Tasks:
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

# Critérios de Aceitação
* Colocar artefato na Wiki
* Ter a logotipo 
* Ter as cores 
* Ter uso das cores
* Ter a tipografia
* Modo de uso da marca 
* Modo de não uso da marca

**Comment by youssef-md** [comment]
Criem todos os assets no figma em que criamos os RPs, fica mais fácil para verem os RPs caso queiram e deixa tudo em um só lugar 
https://www.figma.com/file/3Y4xtaVPvTjbi7nUWRPah4/Desenho-2019.2

**Comment by youssef-md** [comment]
Vamos comentar todas as ideias de logos neste figma, pra ficar mais fácil para votar e ter novas ideias combinando-os :smile_cat: 

https://www.figma.com/file/y5PDTSG8StNgFGwo3uQ4vP/Pax-Logos?node-id=0%3A1
