### ISSUE TITLE
Diagramas (BPMN) 

### ISSUE THREAD

**Issue by EsioFreitas** [pax-app/Wiki#53]
# Descrição da Issue
Criar padrão que deve ser seguido do BPMN.

## Tasks:
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

# Critérios de Aceitação
* Lista de todos processo que devem ser mapeados
* Estar na wiki
* Exemplo de diagrama

**Comment by rogerioo** [comment]
@Matheusss03 Coloca aqui no comentário o que foi decidido por favor :smile:

**Comment by Matheusss03** [comment]
## Descrição
Todos devemos realizar um protótipo de modelagem das etapas que iremos realizar na disciplina. 
Inicialmente serão modeladas 2 etapas: *Elaborar Artefatos Iniciais do Projeto* e *Definir Metodologias e Abordagens*

## Tarefas
**Elaborar Artefatos Iniciais do Projeto**:
* @MarcosNBJ 
* @lucasdutraf 
* @kaiqueborges 
* @gabrielalbino 
* 

**Definir Metodologias e Abordagens**:
* @Matheusss03 
* @FabianaRibas 
* @fepas 
*
*

## Metodologia
1. Modelar o processo que ficou responsável usando o [Bizagi](https://www.bizagi.com/pt) ou o [Heflo](https://www.heflo.com/pt-br/)
2. Exportar a imagem da modelagem e colocar nessa issue #53

## Exemplo
![](https://i.imgur.com/jA9FU3Y.png)

**Comment by lucasdutraf** [comment]
@Matheusss03 coloca a v1.0 e os modelos que você fez na Wiki pra a gente poder fechar a issue

**Comment by lucasdutraf** [comment]
Essa issue pode ser fechada? @Matheusss03 coloca os modelo na wiki

**Comment by rogerioo** [comment]
Os modelos já estão na Wiki
