### ISSUE TITLE
Escolher Paletas de cores

### ISSUE THREAD

**Issue by EsioFreitas** [pax-app/Wiki#54]
# Descrição da Issue
Escolher paletas de cores da aplicação

**Comment by EsioFreitas** [comment]
Galera, segue uns links para ajudar na escolha das cores: 
* https://webgradients.com/
* https://colorhunt.co/
* https://www.materialui.co/colors
* https://www.0to255.com/
* https://coolors.co/
* https://brandcolors.net/
* https://colourco.de/
* https://lokeshdhakar.com/projects/color-thief/

**Comment by EsioFreitas** [comment]
Deem uma olhada nisso tbm 
https://material.io/resources/color/#!/?view.left=0&view.right=0&primary.color=0288D1

**Comment by EsioFreitas** [comment]
Paleta de cores inspirada na teoria das cores 

![image](https://user-images.githubusercontent.com/34384624/63938023-3e152d80-ca3a-11e9-9fa1-d098909404f3.png)

**Comment by EsioFreitas** [comment]
Teoria para justificar as cores 
![image](https://user-images.githubusercontent.com/34384624/63938070-57b67500-ca3a-11e9-8704-7f11c3f8ec73.png)

**Comment by EsioFreitas** [comment]
Cores com os tons e quais cores de fontes sao permitidos

![Group 4](https://user-images.githubusercontent.com/34384624/63938189-99472000-ca3a-11e9-873f-a659c7920bfe.png)

**Comment by EsioFreitas** [comment]
![Group 4 (5)](https://user-images.githubusercontent.com/34384624/63941415-fa262680-ca41-11e9-9a5e-9e954095c9ab.png)

**Comment by gabrielalbino** [comment]
A paleta de cores acima foi a escolhida.
