### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by EsioFreitas** [pax-app/Wiki#6]
Deve criar um Benchmarking dos possíveis concorrentes da aplicação para analise de funcionalidades. 

Exemplo:
![image](https://user-images.githubusercontent.com/34384624/63063089-a1974b00-bed1-11e9-8bd9-ec5398a347d1.png)

**Comment by Matheusss03** [comment]
Alguns "concorrentes" do nosso app:

- [Sem Patrão](https://play.google.com/store/apps/details?id=br.com.usemobile.sempatrao&hl=pt_BR)
- [GetNinjas](https://play.google.com/store/apps/details?id=br.com.getninjas.pro&hl=pt_BR)
- [Bico Certo](https://play.google.com/store/apps/details?id=com.bicocerto&hl=pt_BR)
- [Mão de Obra](https://play.google.com/store/apps/details?id=br.com.maoDeObra.MaoDeObra)
- [Habitissimo: Melhorando sua casa](https://play.google.com/store/apps/details?id=com.habitissimo.app.part)

**Comment by MarcosNBJ** [comment]
Versão inicial do documento criado no [drive](https://drive.google.com/open?id=1i1oqf0XltrEuVlQHSPha_zu3xm64iOqKAP1S7OOigWs) para preenchimento do Benchmarking em acordo com o template sugerido. Alguns dados de concorrentes foram coletados em [outros documentos](https://drive.google.com/drive/folders/1K77AIPtmWErm6CgWb873jJ2Y-Pv9fXSY?usp=sharing) e também podem ser utilizados para facilitar a pesquisa.

**Comment by gabrielalbino** [comment]
Adicionei as plataformas abaixo no documento do Marcos

Fast Salon | Me Ajuda App | Workana | Freelancers
-- | -- | -- | --
