### ISSUE TITLE
 Wireframe Condensado com Fluxos

### ISSUE THREAD

**Issue by EsioFreitas** [pax-app/Wiki#67]
# Descrição da Issue
Fazer um wireframe para validar o fluxo do aplicativo e poder fazer os testes. 

## Tasks:
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

# Critérios de Aceitação
* Cobrir as user history do backlog
* **NÃO** ter a identidade visual da aplicação
* Estar na wiki

**Comment by youssef-md** [comment]
Segue o Figma que estamos utilizando https://www.figma.com/file/cmUWUCrBPoO11hGFuuNu7z/Wireframe-TOP?node-id=0%3A1
