### ISSUE TITLE
Diagrama de Ritos Semanais

### ISSUE THREAD

**Issue by EsioFreitas** [pax-app/Wiki#69]
# Descrição da Issue
Fazer diagrama de ritos semanais

## Tasks:
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

# Critérios de Aceitação
* Colocar artefato na Wiki
* Seguir os padrões do BPMN

**Comment by rogerioo** [comment]
@FabianaRibas e @Matheusss03 Eles já estão na wiki?

**Comment by rogerioo** [comment]
Os documentos estão disponíveis na Wiki!
