### ISSUE TITLE
Mapa Mental

### ISSUE THREAD

**Issue by EsioFreitas** [pax-app/Wiki#7]
Entregar documento de NFR com as conclusões para a tecnologia

**Comment by youssef-md** [comment]
Eu e @rogerioo iremos fazer um mapa mental, pois percebemos que seria o melhor a se fazer para as tecnologias do projeto

**Comment by rogerioo** [comment]
Versão 1.0
![Tecnologias_](https://user-images.githubusercontent.com/42387946/63228462-a60d7d80-c1c9-11e9-8e0d-02ecb223d881.png)
