### ISSUE TITLE
Diagrama de Fluxo de Atividades da Aplicação

### ISSUE THREAD

**Issue by EsioFreitas** [pax-app/Wiki#72]
# Descrição da Issue
Fazer diagrama de Fluxo de Atividades da Aplicação

# Critérios de Aceitação
* Colocar artefato na Wiki
* Seguir os padrões do BPMN

**Comment by lucasdutraf** [comment]
Fluxograma discutido pelo grupo:
![image](https://user-images.githubusercontent.com/31940073/64274387-aae86600-cf19-11e9-9227-f34015d63a7d.png)
![image](https://user-images.githubusercontent.com/31940073/64274393-ae7bed00-cf19-11e9-9a68-8bf0c8c192c5.png)
![image](https://user-images.githubusercontent.com/31940073/64274402-b2a80a80-cf19-11e9-8fbe-21c62c5d12ac.png)
![image](https://user-images.githubusercontent.com/31940073/64274413-b6d42800-cf19-11e9-8914-38ed34fcd6cd.png)
