### ISSUE TITLE
Documento de Arquitetura v0.0

### ISSUE THREAD

**Issue by lucasdutraf** [pax-app/Wiki#73]
# Descrição da Issue
Conforme acordado pelo grupo, será elaborada uma versão inicial do documento de arquitetura, sendo ele mais simplificado e trazendo propostas para futura implementação do time.

## Tasks:
- [x] Representação arquitetural
- [x] Restrições e metas arquiteturais 
- [ ] Visão de casos de uso

# Critérios de Aceitação
* Colocar artefato na Wiki

**Comment by lucasdutraf** [comment]
![image](https://user-images.githubusercontent.com/31940073/64862121-1b714000-d608-11e9-839d-43fef6e5218a.png)
Agradecimentos especiais ao @youssef-md , @MarcosNBJ , @rogerioo pela participação no processo criativo.

**Comment by youssef-md** [comment]
Fiz um doc no Drive com um resumo geral de microsserviços e de como utilizá-lo, [aqui](https://docs.google.com/document/d/1eD63mgW_cpP2b3_X9wkvSi_RAxEl008FkC49YDmezik/edit)
