### ISSUE TITLE
Briefing

### ISSUE THREAD

**Issue by EsioFreitas** [pax-app/Wiki#8]
Entregar document de briefing respondendo as seguintes duvidas:
* Por que do produto?
* Para quem está entregando valor?
* Quando e onde o usuário vai usar o produto? Qual e o contexto do usuário?
* Qual eh a solução com maior impacto e menor esforço?
* Como saber se a solução está funcionando?

Referencia:
https://docs.google.com/document/d/1Ce_W5hReHlpsoIqiCrv84c7o8TK4QY2BpxQS9PnzjZc/edit

**Comment by FabianaRibas** [comment]
### Versão: 1.0
https://docs.google.com/document/d/1i2tgxyKY6vKoWERJHGVZTVC9kB3-J5dmrmf0PUmzFAg/edit?usp=sharing
