### ISSUE TITLE
Diagrama de Classes BackEnd

### ISSUE THREAD

**Issue by youssef-md** [pax-app/Wiki#89]
# Descrição da Issue
Deve ser entregue diagramas com a maior quantidade de classes que conseguir de todo o back-end do app, podendo ser separados por serviços

## Tasks:
- [x] Adicionar classes
- [x] Adicionar métodos
- [x] Adicionar relacionamentos
- [ ] Avaliar com a equipe em reunião
- [ ] Refatorar para consistência com outros modelos

# Critérios de Aceitação
* Colocar artefato na Wiki

**Comment by kaiquebuilds** [comment]
V1 do diagrama:

![Diagrama de classes Pax](https://user-images.githubusercontent.com/14828276/64902608-aee65780-d680-11e9-9fac-54ccb4c1eb7c.jpg)

Algumas questões foram levantadas para serem resolvidas junto à equipe e à professora na dinâmica
