### ISSUE TITLE
Brainstorm de ideias para o app

### ISSUE THREAD

**Issue by gabrielalbino** [pax-app/Wiki#9]
# Descrição da Issue
Os membros do grupo comentarão nessa issue as ideias para o app

# Assignees
@MarcosNBJ @kaiqueborges @Matheusss03 @fepas @gabrielalbino @lucasdutraf @EsioFreitas @FabianaRibas @rogerioo

**Comment by gabrielalbino** [comment]
* Avaliação para contratantes e contratados
* Tag de usuário novo
* Avaliação somente se o usuário tiver solicitado o serviço

**Comment by lucasdutraf** [comment]
- Buscar melhor maneira de adquirir informações do usuário
- Múltiplos serviços podem ser prestados por um único prestador de serviços

**Comment by Matheusss03** [comment]
- Avaliação individual por tipo de serviço por pessoa
