### ISSUE TITLE
Diagrama de Classes FrontEnd	

### ISSUE THREAD

**Issue by youssef-md** [pax-app/Wiki#90]
# Descrição da Issue
Deve ser entregue diagramas contendo as classes que serão utilizadas no Flutter na etapa de desenvolvimento, podendo ser separados por features ou algo do tipo para facilitar a visualização

## Tasks:
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

# Critérios de Aceitação
* Colocar artefato na Wiki

**Comment by fepas** [comment]
#### Dart Class Diagram Generator
A small command line utility to generate a class (UML or similar) diagram from a Dart package.
https://pub.dev/packages/dcdg

**Comment by lucasdutraf** [comment]
Issue fechada devido a decisão do grupo visando necessidades do projeto.
