### ISSUE TITLE
Diagrama de Estados

### ISSUE THREAD

**Issue by youssef-md** [pax-app/Wiki#95]
# Descrição da Issue
Deve ser entregue a maior quantidade de diagramas de estados que conseguir, podendo ter como base outros documentos já produzidos, só lembre de os referenciar neste artefato

## Tasks:
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

# Critérios de Aceitação
* Colocar artefato na Wiki

**Comment by FabianaRibas** [comment]
### Diagrama de estados do Chat(V1.0)

![Untitled Diagram (5)](https://user-images.githubusercontent.com/38467658/64978525-1ae8db80-d88c-11e9-92dd-a496c67befb0.png)

### Diagrama de estados do Payment(v1.0)

![Untitled Diagram (6)](https://user-images.githubusercontent.com/38467658/64978542-263c0700-d88c-11e9-9a3c-c08c242b30e9.png)

**Comment by FabianaRibas** [comment]
Não consegui validar com a professora ainda, por isso não subi pra wiki.
